template_project/template_app/urls.py
from django.urls import path
from . import views

app_name = "template_app"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("other/", views.other, name="other"),
    path("base/", views.base, name="base"),
    path("relative/", views.relative, name="relative")
]

template_project/template_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from template_app import views
from template_app import urls as app_url

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("", include(app_url)),
]

template_project/template_app/models.py
from django.db import models

# Create your models here.

template_project/template_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    my_dict = {'text':"Hello world", 'number':100}
    return render(request, "template_app/index.html", my_dict)

def relative(request):
    return render(request, "template_app/relative_url_template.html")

def other(request):
    return render(request, "template_app/other.html")

def base(request):
    return render(request, "template_app/base.html")

template_project/templates/template_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'template_app:other' %}">Other</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <div class="container">
        {% block body_block %}


        {% endblock %}
    </div>
</body>
</html>

template_project/templates/template_app/index.html
<!DOCTYPE html>
{% extends 'template_app/base.html' %}
    {% block body_block %}

        <h1>Welcome to your Index</h1>
        <h2>This has been extended</h2>
        <h3>{{text|cut:"world"}}</h3>
        <h3>{{number|add:"99"}}</h3>

    {% endblock %}

template_project/templates/template_app/other.html
<!DOCTYPE html>
{% extends 'template_app/base.html' %}
    {% block body_block %}
        <h1>Welcome to your Other page</h1>
        <h2>This is other.html, it now extends base.html</h2>
    {% endblock %}

template_project/templates/template_app/relative_url_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to relativae url template page</h1>

    <a href="{% url 'template_app:other' %}">Other page</a>
    <a href="{% url 'admin:index' %}">Admin page</a>
    <a href="{% url 'index' %}">Link to Index</a>
</body>
</html>